### PR TITLE
replace param 'key' with header 'x-api-key'

### PR DESCRIPTION
**Pull request by rikeshi**
in GalaxyClient.make_get_request()

As mentioned by @nsoranzo in galaxyproject/galaxy#11375. This also fixes the 'key' error when making an API request.
Not sure if I did it right, but it's a starting point.

### CODE REVIEW

**Review by simonbray — APPROVED** [review]

**Comment by simonbray** [comment]
Actually, I guess this applies to all request types, not just GET. Can you update the other methods as well?

**Comment by simonbray** [comment]
You could simply add it to `json_headers` on line 45: https://github.com/galaxyproject/bioblend/blob/8c20180e5a57bc377d0af1e5d0ebea9cd6248884/bioblend/galaxyclient.py#L45

**Comment by nsoranzo** [comment]
@rikeshi Thanks a bunch for starting this! I've pushed a commit applying to all other REST methods and cleaned it up, can you double check please?

**Comment by rikeshi** [comment]
Thanks for cleaning it up @nsoranzo ! Looks good to me.

**Review by nsoranzo — APPROVED** [review]

**Pull request merged**
