### PR TITLE
WIP: Add support for Python >= 3.3 using six package.

### PR DESCRIPTION
**Pull request by nsoranzo**
TODO: dictionary iterator methods.

Also, still not possible to test on Python3 because of poster and boto packages.

### CODE REVIEW

**Comment by jmchilton** [comment]
This is awesome @nsoranzo! Does the WIP mean you don't want me to merge this? Seems like an atomic commit to me - we can always follow up with fixes for dictionary iteration, boto, and poster?

**Comment by simleo** [comment]
Nice work indeed! I have only one concern, and I've expressed it as PR #132 :)

**Comment by nsoranzo** [comment]
@jmchilton If your review is positive, please merge! The WIP means that the 2nd point "Switch all changed imports to use six.moves, at this point all the files would be importable within Python 3 - which would help downstream projects like planemo." in #97 is not completed yet.

**Comment by jmchilton** [comment]
Awesome.

**Pull request merged**
