### PR TITLE
Small project changes.

### PR DESCRIPTION
**Pull request by nsoranzo**
- Add latest PyPI version and RTD badges.
- Update PyPI classifiers.

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1:

**Comment by afgane** [comment]
Glad to see it out of Alpha :)
Should we prepare another release? Or wait and match it up with the next Galaxy release?

**Comment by jmchilton** [comment]
I would love to see a release pre-GCC so there is some chance planemo can support Python 3 by then. Not super important though and there is some chance I wouldn't get around to doing a planemo release for that anyway.

**Comment by nsoranzo** [comment]
+1 to a pre-GCC2015 release, so I can say that Python 3 is officially supported. Should we go for a 0.6 version?

**Comment by afgane** [comment]
Sounds good. 
v0.6 is what I was thinking as well.

**Comment by afgane** [comment]
@jmchilton: do I remember correctly that you have a script that automatically creates a CHANGELOG template based on commits?

**Comment by jmchilton** [comment]
What I have is this - https://github.com/galaxyproject/planemo/blob/master/scripts/bootstrap_history.py.

I sort of work manually through git PRs, issues, and then go back and look for individual commits and run it for anything interesting. It will add an RST link and short description to a CHANGELOG.rst. So it is semi-automated and targets RST not MD. The advantage of RST of markdown is including it in readthedocs.

Usage is something like:
```
python scripts/bootstrap_history.py pr102 [MSG]
python scripts/bootstrap_history.py issue104 [MSG]
python scripts/bootstrap_history.py commithash [MSG]
```

If MSG isn't found - it generates one from stuff in github. There are a couple markers I put in the CHANGELOGs so the script knows where to add stuff.

**Comment by afgane** [comment]
Here's a first pass at the CHANGELOG so please see if I captured the major changes and edit as you find appropriate:
https://github.com/galaxyproject/bioblend/blob/master/CHANGELOG.md

(I ended up generating that by hand)

**Comment by nsoranzo** [comment]
@afgane I have merged a pending PR and updated the CHANGELOG, I think it's good to go!

**Comment by afgane** [comment]
@nsoranzo @jmchilton the release is out.

**Comment by nsoranzo** [comment]
Thanks a lot @afgane!

**Pull request merged**
