### PR TITLE
fix #253?

### LINKED ISSUE #253: Issue downloading datasets
cc @bgruening from GIEs I'm seeing the inability to download datasets because of the following line.

https://github.com/galaxyproject/bioblend/blob/f946b3ab5ef7362f0af34d0324b6087eb3d29d5f/bioblend/galaxy/datasets/__init__.py#L108

the requests are made unauthenticated and fail. Adding the API key to the request fixes it. It presents as the following exception:

https://sentry.denbi.uni-freiburg.de/share/issue/322e36323432/

### PR DESCRIPTION
**Pull request by erasche**

### CODE REVIEW

**Comment by nsoranzo** [comment]
Thanks @erasche!

**Comment by nsoranzo** [comment]
@erasche Do you need a BioBlend release for this?

**Comment by nsoranzo** [comment]
@erasche I've uploaded bioblend 0.11.0 to PyPI, sorry for the delay.

**Comment by erasche** [comment]
Perfect, thanks! 

cc @mtekman who had the original issue.

**Pull request merged**
