### PR TITLE
Add get_datasets() function

### PR DESCRIPTION
**Pull request by simonbray**
Add function to access `/api/datasets` to get a list of all datasets, with `limit` and `offset` parameters.

### CODE REVIEW

**Comment by bgruening** [comment]
Restarted the failing tests, looked like a network timeout.

**Comment by simonbray** [comment]
One test still failing, but it doesn't seem to relate to this PR.

**Comment by nsoranzo** [comment]
Definitely not related, Galaxy use of conda on macOS Python3 is broken due to https://github.com/pypa/virtualenv/issues/1704 , which is closed but not solved unfortunately.

**Comment by simonbray** [comment]
In that case, can you have a look at whether this is ready to merge @nsoranzo?

**Comment by nsoranzo** [comment]
Thanks @simonbray!

**Pull request merged**
