### PR TITLE
Reflow large datastructures for TS docs

### PR DESCRIPTION
**Pull request by erasche**

### CODE REVIEW

**Comment by erasche** [comment]
E.g. for the problem: http://bioblend.readthedocs.org/en/latest/api_docs/toolshed/all.html#bioblend.toolshed.repositories.ToolShedClient.get_repository_revision_install_info

**Comment by nsoranzo** [comment]
I'm trying to uniformly use `pprint.pprint()` style for docs, see e.g. commit 63b544df70afa354939f24ed12625e4e67a35955 . Can you change to the same style?

**Comment by erasche** [comment]
Hmm, OK. Yes, I can do that. 

I had been more going for legibility and balance/symmetry of whitespace.

**Comment by erasche** [comment]
@nsoranzo fixed.

**Comment by nsoranzo** [comment]
Thanks @erasche!

**Pull request merged**
