### PR TITLE
Add ``published`` parameter to ``HistoryClient.get_histories()``

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix https://github.com/galaxyproject/bioblend/issues/339

### CODE REVIEW

**Comment by simonbray** [comment]
@nsoranzo, thanks for adding this, this is very handy. However, I don't think it fixes @mtekman's issue. For that an option would also need to be added to filter on slug.

**Comment by nsoranzo** [comment]
Yep, sorry, it doesn't fix it at all actually, since this let a user filter only their own published/non-published histories!

**Comment by simonbray** [comment]
True - I'm afraid I didn't test this until now :(

It looks like you really need to use `/api/histories/published` then.

**Comment by nsoranzo** [comment]
Indeed, we need to add a separate method to `HistoryClient`.

**Pull request merged**
